# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

plugin 'cocoapods-keys', {
:project => "SearchApp",
:keys => [
  "pixabayApiKey"
]}

target 'SearchApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SearchApp
pod 'Kingfisher'
pod 'NVActivityIndicatorView'
pod 'ReachabilitySwift'

  target 'SearchAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
